version: '2'
services:
  zk:
    image: jplock/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka1:
    image: ches/kafka:0.10.2.1
    ports:
      - "9092:9092"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ADVERTISED_PORT: 9092
      ZOOKEEPER_CONNECTION_STRING: zk:2181
  kafka2:
    image: ches/kafka:0.10.2.1
    ports:
      - "9093:9092"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ADVERTISED_PORT: 9093
      ZOOKEEPER_CONNECTION_STRING: zk:2181
  kafka3:
    image: ches/kafka:0.10.2.1
    ports:
      - "9094:9092"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ADVERTISED_PORT: 9094
      ZOOKEEPER_CONNECTION_STRING: zk:2181
