version: '2'
services:
  zk:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
      - "9093:9093"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9092,SSL://${HOST_IP}:9093"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      # - ./testHelpers/log4j.properties:/opt/kafka/config/log4j.properties
  kafka2:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9094:9094"
      - "9095:9095"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9094,SSL://:9095"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9094,SSL://${HOST_IP}:9095"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      # - ./testHelpers/log4j.properties:/opt/kafka/config/log4j.properties
  kafka3:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9096:9096"
      - "9097:9097"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9096,SSL://:9097"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9096,SSL://${HOST_IP}:9097"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      # - ./testHelpers/log4j.properties:/opt/kafka/config/log4j.properties
